version: '3.8'

networks:
  custom_bridge:
    external: true

x-def-logging: &default-logging
  logging:
    driver: "loki"
    options:
      loki-url: "http://192.168.0.10:3100/loki/api/v1/push"
      loki-batch-size: "100"
      loki-retries: 2
      loki-max-backoff: 1000ms
      loki-timeout: 1s
      loki-external-labels: "container={{.Name}},image={{.ImageName}},id={{.ID}}"



services:
  web:
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - 1026:1026
    command: scripts/web/startup.sh -m -l
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./:/code
      - ./:/app
    networks:
      - custom_bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    <<: *default-logging

  centrifugo:
    image: centrifugo/centrifugo:v6
    ports:
      - 8000:8000
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - custom_bridge
    restart: on-failure
    <<: *default-logging

  redis:
    container_name: messenger_redis
    image: redis:6.2.4
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - custom_bridge
    <<: *default-logging

  loki:
    image: grafana/loki:2.9.14
    container_name: loki
    environment:
      TZ: ${SYSTEM_TIMEZONE:-Europe/Moscow}
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      custom_bridge:
        ipv4_address: 192.168.0.10

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - TZ=${SYSTEM_TIMEZONE:-Europe/Moscow}
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/provisioning/dashboards
    ports:
      - "3000:3000"
    networks:
      - custom_bridge
    <<: *default-logging
