# Generated by Django 4.2.11 on 2025-04-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('chat_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group')], max_length=10)),
            ],
            options={
                'verbose_name': 'chat',
                'db_table': '"messenger_encrypted"."chat"',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('public_key', models.TextField()),
            ],
            options={
                'verbose_name': 'user',
                'db_table': '"messenger_encrypted"."user"',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encrypted_payload', models.BinaryField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.user')),
            ],
            options={
                'verbose_name': 'message',
                'db_table': '"messenger_encrypted"."message"',
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.user')),
            ],
            options={
                'verbose_name': 'chat_participant',
                'db_table': '"messenger_encrypted"."chat_participant"',
            },
        ),
    ]
