# Generated by Django 4.2.11 on 2025-05-20 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageRead",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="messenger.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="messenger.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "message_read",
                "db_table": '"messenger_encrypted"."message_read"',
                "unique_together": {("message", "user")},
            },
        ),
    ]
