@startuml
skinparam componentStyle rectangle
skinparam activityDiamondFontSize 30
skinparam activityArrowFontSize 24
skinparam PackageFontSize 24
skinparam ComponentFontSize 34
skinparam DatabaseFontSize 34


left to right direction

package "Frontend" {
  [React + TypeScript\n(Пользовательский интерфейс)] as ReactTS
}

package "WebSocket Layer" {
  [Centrifugo\n(Передача сообщений в реальном времени)] as Centrifugo
}

package "Backend" {
  [Django\n(Админка, миграции)] as Django
  [FastAPI\n(API и бизнес-логика)] as FastAPI
}

package "Data Layer" {
  database "PostgreSQL\n(Постоянные данные)" as PostgreSQL
  database "Redis\n(Кэш, сессии, токены)" as Redis
}

package "Monitoring & Logging" {
  [Prometheus\n(Сбор метрик)] as Prometheus
  [Grafana\n(Дашборды и визуализация)] as Grafana
  [Loki\n(Централизованное логирование)] as Loki
}

Centrifugo <-- ReactTS : WebSocket
Centrifugo --> FastAPI : Входящие сообщения

FastAPI -> PostgreSQL : Чтение/Запись
FastAPI -> Redis : Кэш и токены
Django --> PostgreSQL : Миграции/админка

Prometheus -> FastAPI : Метрики
Prometheus --> PostgreSQL : Метрики
Grafana --> Prometheus : Визуализация метрик
FastAPI -> Loki : Логи

Centrifugo --> Loki : Логи
Grafana -> Loki : Просмотр логов

@enduml
