@startuml
title Передача сообщения от отправителя к получателю
actor "Sender Client\n(React + TypeScript)\n\nВася" as Sender_Vasya

actor "Recipient Client\n(React + TypeScript)\n\nПетя" as Recipient_Petya

participant "FastAPI Backend" as Backend

Sender_Vasya-> Backend: POST /api/v1/message --- Отправляет чат, ID отправителя, + зашифрованную Merge Private Key полезную нагрузку(сообщение)

Recipient_Petya <-> Backend: GET/api/v1/message/by-chat/{chat_id} --- Получает зашифрованное сообщение из бекенда

Recipient_Petya  -> Recipient_Petya: Достает из local storage Merge Private Key и с его помощью дешифрует полученное сообщение

@enduml